


if (T) {
  options("repos" = c(CRAN = "https://mirrors.tuna.tsinghua.edu.cn/CRAN/"))
  options(BioC_mirror = "http://mirrors.ustc.edu.cn/bioc/") 
  library(e1071)
  library(parallel)
  library(preprocessCore)
  library(sva)
  library(ggplot2)
  library(survminer)
  library(survival)
  library(rms)
  library(randomForest)
  library(pROC)
  library(glmnet)
  library(pheatmap)
  library(timeROC)
  library(vioplot)
  library(corrplot)
  library(forestplot)
  library(survivalROC)
  library(beeswarm)
  library(Biostrings)
  library(pheatmap)
  library(stringr)
  library(dplyr)
  library(RColorBrewer)
  library(tibble)
  library(cowplot)
  library(ggcorrplot)
  library(tidyverse)
  library(plyr)
  library(circlize)
  library(SummarizedExperiment)
  library(ggsci)
  library(ComplexHeatmap)
  library(pastecs)
  library(fs)
  library(pastecs)
  library(scales)
  library(ggkm)
  library(survcomp)
  library(pbapply)
  library(survival)
  library(pec)
  library(caret)
  library(leaps)
  library(randomForestSRC)
  library(mlr3)
  library(mlr3viz)
  library(mlr3learners)
  library(mlr3verse)
  library(mlr3tuning)
  library(data.table)
  library(mlr3proba)
  library("magrittr")
  library(mlr3extralearners)
  library(iml)
  library("DALEX")
  library(DALEXtra)
  library(dcurves)
  library(MASS)
  library(survival)
  library(risksetROC)
  library(ggDCA)
  library(beepr)
  library(BRRR)
  options(stringsAsFactors = FALSE)
}



########################################################################
####################################' @subgroup
########################################################################


options("scipen" = 6, "digits" = 6)
##' Extract hazard ratio and confidence intervals from a coxph object
##'
##' Convenience function to extract hazard ratio and confidence intervals from a coxph object,
##' as generated by a call to coxph(), comparing survival times between two groups
##' @param coxphData coxph object; coxphData <- coxph(Surv(TTE, Cens) ~ group, data=df)
##' @author Dorothee Nickles
##' @export
##' @import survival
getHRandCIfromCoxph <- function(coxphData) {
  stopifnot(is(coxphData, "coxph"))

  tmp <- cbind(
    summary(coxphData)$coef[,
      c("Pr(>|z|)", "exp(coef)"),
      drop = FALSE
    ],
    summary(coxphData)$conf[,
      c("lower .95", "upper .95"),
      drop = FALSE
    ]
  )
  colnames(tmp) <- c("P", "HR", "CI_low_0.95", "CI_up_0.95")
  return(round(tmp, digits = 4))
}

##' Extract hazard ratio and confidence intervals from a coxph object of subgroup analysis
##'
##' @param pdata     data combine variables, time, and status;
##' @param variable  object that have several levles;
##' @param time      follow up
##' @param status    outcome event
##' @param object    that use to calculate coxph fit
##' @author Dongqiang Zeng
##' @export
##' @import survival
############
############
Subgroup_survival_analysis <- function(pdata, time = "time", status = "status", variable, object) {
  P <- 1
  HR <- 1
  CI_low_0.95 <- 1
  CI_up_0.95 <- 1
  result <- data.frame(P, HR, CI_low_0.95, CI_up_0.95, row.names = "defult")
  pdata <- as.data.frame(pdata)
  for (sig in variable) {
    ind <- which(colnames(pdata) == sig)
    tmp <- pdata[!is.na(pdata[, ind]), ]
    if (dim(tmp)[1] == 0) {
      next
    }
    tmp[, ind] <- as.factor(as.character(tmp[, ind]))
    result2 <- data.frame(P, HR, CI_low_0.95, CI_up_0.95, row.names = "defult")
    nl <- nlevels(tmp[, ind])
    for (i in 1:nl) {
      tmp1 <- tmp[as.character(tmp[, ind]) == names(summary(tmp[, ind]))[i], ]
      if (dim(tmp1)[1] == 0) {
        next
      }
      fit <- coxph(Surv(tmp1[, time], tmp1[, status]) ~ tmp1[, object], data = tmp1)
      result1 <- getHRandCIfromCoxph(fit)
      rownames(result1) <- paste(sig, levels(tmp[, ind])[i], sep = "_")
      result2 <- rbind(result2, result1)
    }
    result <- rbind(result, result2)
  }
  result[result > 100] <- Inf
  return(result[-c(grep(rownames(result), pattern = "defult")), ])
}
###########



load("HF_metadata.rda")
df <- dataset3 %>% dplyr::select(-c("Name", "ID"))
rm(dataset3)
df$ID <- c(paste0("G", c(1:712)))
row.names(df) <- df$ID
df <- df %>% dplyr::select(-c("ID"))

if (T) {
  df <- df %>% mutate(
    NYHA = case_when(
      NYHA %in% "I" | NYHA %in% "II" ~ 1,
      NYHA %in% "III" | NYHA %in% "IV" ~ 2
    )
  )
  df <- df %>% mutate(
    CKD_stage = case_when(
      CKD_stage %in% "I" | CKD_stage %in% "II" ~ 1,
      CKD_stage %in% "IIIa" | CKD_stage %in% "IIIb" ~ 2,
      CKD_stage %in% "IV" | CKD_stage %in% "V" ~ 3,
    )
  )
  df <- df %>% mutate(
    HF_subtype = case_when(
      HF_subtype %in% "HFpEF" ~ 1,
      HF_subtype %in% "HFmrEF" ~ 2,
      HF_subtype %in% "HFrEF" ~ 3
    )
  )
  df <- df %>% mutate(
    Age = case_when(
      Age > 65 ~ 1,
      Age <= 65 ~ 2
    )
  )
}
df$MACE_Censor <- as.numeric(as.character(df$MACE_Censor))
df$ACM_Censor <- as.numeric(as.character(df$ACM_Censor))
df$Gender <- ifelse(df$Gender %in% c("female"), 0, 1)

class <- ZG_class_fordf(df)
class
desc_number <- stat.desc(df)
list <- colnames(df)[rowSums(is.na(t(desc_number))) > 1]
list
df[, list] <- lapply(df[, list], as.numeric)


list2 <- colnames(df)[rowSums(is.na(t(desc_number))) == 0]
list2
list2 <- list2[-which(list2 %in% c("MACE_Censor", "MACE", "ACM", "ACM_Censor"))]
list2
list2 <- list2[-which(list2 %in% c("Gender", "NYHA", "HTN", "HF_subtype", "CKD_stage", "Age"))]
list2
df[, list2] <- lapply(df[, list2], scale)
expr.surv_all <- df

if (T) {
  load("val_dd_list.rda")
  rm(fit, val_dd_list, task_test, task_train, task_meta)
  load(file = "ACM_expr.surv.rda")
  lrn_xgboost <- lrn("surv.xgboost",
    max_depth = 3, eta = 0.01, gamma = 0, subsample = 0.75, colsample_bytree = 0.8,
    min_child_weight = 3, lambda = 1, alpha = 0, nrounds = 500
  )
  measures <- c("surv.cindex")
  resampling_HD <- rsmp("holdout", ratio = 0.7)
  set.seed(1771)
  rr_HD <- resample(as_task_surv(expr.surv, time = "ACM", event = "ACM_Censor")$select(rid), lrn_xgboost, resampling_HD, store_models = T)
  index_HD <- msrs(measures) %>% rr_HD$aggregate()
  index_HD
}

if (T) {
  task <- as_task_surv(expr.surv_all, time = "ACM", event = "ACM_Censor")
  task
  task_train <- task$filter(rr_HD$resampling$train_set(1))
  task_train
  task <- as_task_surv(expr.surv_all, time = "ACM", event = "ACM_Censor")
  task
  task_test <- task$filter(rr_HD$resampling$test_set(1))
  task_test
  task <- as_task_surv(expr.surv_all, time = "ACM", event = "ACM_Censor")
  task
  task_meta <- task
  task_meta
  val_dd_list_all <- list()
  val_dd_list_all[[1]] <- task_train$data()
  val_dd_list_all[[2]] <- task_test$data()
  val_dd_list_all[[3]] <- task_meta$data()
  names(val_dd_list_all) <- c("Train_1", "Test_2", "Meta_3")
  val_dd_list_all <- lapply(val_dd_list_all, function(x) {
    as.data.frame(x)
  })

  task <- as_task_surv(expr.surv, time = "ACM", event = "ACM_Censor")
  task$select(rid)
  task
  task_train <- task$filter(rr_HD$resampling$train_set(1))
  task_train
  task <- as_task_surv(expr.surv, time = "ACM", event = "ACM_Censor")
  task$select(rid)
  task
  task_test <- task$filter(rr_HD$resampling$test_set(1))
  task_test
  task <- as_task_surv(expr.surv, time = "ACM", event = "ACM_Censor")
  task$select(rid)
  task
  task_meta <- task
  task_meta

  fit <- rr_HD$learners[[1]]
  fit$predict(task_test)$score(msrs(measures))
  fit$predict(task_train)$score(msrs(measures))
  fit$predict(task_meta)$score(msrs(measures))

  val_dd_list <- list()
  val_dd_list[[1]] <- task_train$data()
  val_dd_list[[2]] <- task_test$data()
  val_dd_list[[3]] <- task_meta$data()
  names(val_dd_list) <- c("Train_1", "Test_2", "Meta_3")

  identical(
    val_dd_list[[1]]$ACM,
    val_dd_list_all[[1]]$ACM
  )
}



library(xgboost)
rs <- lapply(val_dd_list, function(x) {
  dat.mat <- x %>% as.matrix()
  dtrain <- list(
    data = dat.mat[, 3:ncol(dat.mat)],
    label = dat.mat[, "ACM"] * (-(-1)^(as.numeric(dat.mat[, "ACM_Censor"])))
  )
  Dtrain <- xgb.DMatrix(dtrain$data, label = dtrain$label)
  RS <- predict(fit$model, newdata = Dtrain, type = "risk")
  task <- as_task_surv(x, time = "ACM", event = "ACM_Censor")
  rs <- cbind(x[, 1:2], RS = RS)
  colnames(rs)[3] <- "RS"
  return(rs)
})

C_index <- sapply(rs, function(x) {
  concordance.index(scale(x$RS),
    surv.time = x$ACM, surv.event = x$ACM_Censor,
    method = "noether"
  )$c.index
})
C_index

identical(rs[[1]]$ACM, val_dd_list_all[[1]]$ACM)
identical(rs[[2]]$ACM, val_dd_list_all[[2]]$ACM)
identical(rs[[3]]$ACM, val_dd_list_all[[3]]$ACM)

for (i in names(rs)) {
  if (identical(val_dd_list_all[[i]]$ACM_Censor, rs[[i]]$ACM_Censor)) {
    val_dd_list_all[[i]] <- cbind(val_dd_list_all[[i]], RS = rs[[i]][, 3])
  } else {
    break
  }
  colnames(val_dd_list_all[[i]])[ncol(val_dd_list_all[[i]])] <- "RS"
  val_dd_list_all[[i]] <- val_dd_list_all[[i]] %>%
    dplyr::select(c("ACM", "ACM_Censor", "RS", "Age", "CKD_stage", "NYHA", "HF_subtype", "PCI"))
  val_dd_list_all[[i]] <- cbind(val_dd_list_all[[i]], ProjectID = rep(i, nrow(val_dd_list_all[[i]])))
}


#########################

input <- do.call(rbind, val_dd_list_all)
data2 <- Subgroup_survival_analysis(
  pdata = input,
  time = "ACM", status = "ACM_Censor",
  variable = c("ProjectID", "Age", "NYHA", "HF_subtype", "CKD_stage", "PCI"),
  object = "RS"
)
data2
data.count <- rbind(
  as.data.frame(table(input$ProjectID)),
  as.data.frame(table(input$Age)),
  as.data.frame(table(input$NYHA)),
  as.data.frame(table(input$HF_subtype)),
  as.data.frame(table(input$CKD_stage)),
  as.data.frame(table(input$PCI))
)
data2$count <- data.count$Freq
data2$percentage <- round(100 * data.count$Freq / nrow(input))
data3 <- getHRandCIfromCoxph(coxphData = coxph(Surv(
  time = input[, "ACM"],
  event = input[, "ACM_Censor"]
) ~ RS, data = input))
data3 <- data.frame(data3)
data3$count <- nrow(input)
data3$percentage <- "100"

forestplot_input <- rbind(data3, data2)
forestplot_input$mean <- (forestplot_input$CI_low_0.95 + forestplot_input$CI_up_0.95) / 2

if (T) {
  rownames(forestplot_input)[1] <- "All"
  rownames(forestplot_input)[2] <- "Meta Cohort"
  rownames(forestplot_input)[3] <- "Validation Cohort"
  rownames(forestplot_input)[4] <- "Train Cohort"

  rownames(forestplot_input)[5] <- "Age<=65"
  rownames(forestplot_input)[6] <- "Age>65"

  rownames(forestplot_input)[7] <- "NYHA I/II"
  rownames(forestplot_input)[8] <- "NYHA III/IV"

  rownames(forestplot_input)[9] <- "HFpEF"
  rownames(forestplot_input)[10] <- "HFmrEF"
  rownames(forestplot_input)[11] <- "HFrEF"

  rownames(forestplot_input)[12] <- "Stage I/II"
  rownames(forestplot_input)[13] <- "Stage III"
  rownames(forestplot_input)[14] <- "Stage IV/V"

  rownames(forestplot_input)[15] <- "PCI N"
  rownames(forestplot_input)[16] <- "PCI Y"
}
if (T) {
  Dataset <- data.frame(matrix("", 1, 7))
  row.names(Dataset) <- "Cohort"
  colnames(Dataset) <- colnames(forestplot_input)

  Age <- data.frame(matrix("", 1, 7))
  row.names(Age) <- "Age"
  colnames(Age) <- colnames(forestplot_input)

  Cfg <- data.frame(matrix("", 1, 7))
  row.names(Cfg) <- "Cardiac function grade"
  colnames(Cfg) <- colnames(forestplot_input)

  HF_type <- data.frame(matrix("", 1, 7))
  row.names(HF_type) <- "HF type"
  colnames(HF_type) <- colnames(forestplot_input)

  CKD <- data.frame(matrix("", 1, 7))
  row.names(CKD) <- "CKD stage"
  colnames(CKD) <- colnames(forestplot_input)

  PCI <- data.frame(matrix("", 1, 7))
  row.names(PCI) <- "After PCI"
  colnames(PCI) <- colnames(forestplot_input)
}

forestplot_input <- rbind(
  forestplot_input[1:1, ], Dataset,
  forestplot_input[2:4, ], Age,
  forestplot_input[5:6, ], Cfg,
  forestplot_input[7:8, ], HF_type,
  forestplot_input[9:11, ], CKD,
  forestplot_input[12:14, ], PCI,
  forestplot_input[15:16, ]
)


write.csv(forestplot_input, "subgroup.csv", quote = F)

data <- read.csv("subgroup.csv")
head(data)
dim(data)[1] + 5
np <- ifelse(!is.na(data$count), paste(data$count, " (", data$percentage, ")", sep = ""), NA)
head(np)

tabletext <- cbind(
  c("\nSubgroup", NA, NA, data$X, NA),
  c("No. of\nPatients (%)", NA, NA, np, NA),
  c(
    "Hazard Ratio\n(95% CI)", NA, NA,
    ifelse(!is.na(data$count), paste(round(data$mean, 2), " (", round(data$CI_low_0.95, 2), " to ", round(data$CI_up_0.95, 2), ")", sep = ""), NA), NA
  ),
  c(
    "P-value", NA, NA,
    ifelse(data$P < 0.0001, "<0.0001", round(data$P, 3)), NA
  )
)
tabletext

size <- rep(0.8, length(data$percentage))
size
size[which(is.na(data$percentage))] <- NA
size

p <- forestplot(
  labeltext = tabletext,
  mean = c(1, data$mean, NA), #
  lower = c(1, data$CI_low_0.95, NA),
  upper = c(1, data$CI_up_0.95, NA),
  graph.pos = 3,
  graphwidth = unit(.4, "npc"),
  fn.ci_norm = "fpDrawDiamondCI", #
  col = fpColors(box = "#2C8EAE", lines = "#D1D2D4", zero = "black"),
  boxsize = c(
    NA,
    size,
    NA
  ),
  lwd.ci = 3, ci.vertices.height = 0.1, ci.vertices = TRUE,
  zero = 1,
  lwd.zero = 2,
  grid = structure(c(data[1, ]$mean),
    gp = gpar(col = "grey70", lty = 2, lwd = 3)
  ),
  lwd.xaxis = 2,
  xlab = "Hazard Ratio",
  hrzl_lines = list(
    "1" = gpar(lwd = 2, col = "black"),
    "21" = gpar(lwd = 2, col = "black")
  ),
  txt_gp = fpTxtGp(
    label = gpar(cex = 1.25),
    ticks = gpar(cex = 1.25),
    xlab = gpar(cex = 1.25),
    title = gpar(cex = 1.25)
  ),
  lineheight = unit(.75, "cm"),
  cex = 10,
  colgap = unit(0.5, "cm"),
  mar = unit(rep(1.25, times = 4), "cm"),
  new_page = F
)
p
dev.off()
pdf("subgroup.pdf",
  width = 11.9, height = 8.8
)
p
dev.off()




############################################################
#############################' @====shap
#############################################################
library(xgboost)
rm(list = ls())
load("val_dd_list.rda")
rm(fit, val_dd_list, task_test, task_train, task_meta)
load("HF_metadata.rda")
df <- dataset3 %>% dplyr::select(-c("Name", "ID"))
rm(dataset3)
df$ID <- c(paste0("G", c(1:712)))
row.names(df) <- df$ID
df <- df %>% dplyr::select(-c("ID"))
df <- df[, c("ACM", "ACM_Censor", rid)]
df <- df %>% mutate(
  CKD_stage = case_when(
    CKD_stage %in% "I" ~ 1, CKD_stage %in% "II" ~ 2,
    CKD_stage %in% "IIIa" | CKD_stage %in% "IIIb" ~ 3,
    CKD_stage %in% "IV" ~ 4, CKD_stage %in% "V" ~ 5
  )
)
df <- apply(df, 2, as.numeric) %>% as.data.frame()
expr.surv <- df
lrn_xgboost <- lrn("surv.xgboost",
  max_depth = 3, eta = 0.01, gamma = 0, subsample = 0.75, colsample_bytree = 0.8,
  min_child_weight = 3, lambda = 1, alpha = 0, nrounds = 500
)
measures <- c("surv.cindex")
resampling_HD <- rsmp("holdout", ratio = 0.7)
set.seed(1771)
rr_HD <- resample(as_task_surv(expr.surv, time = "ACM", event = "ACM_Censor"), lrn_xgboost, resampling_HD, store_models = T)
index_HD <- msrs(measures) %>% rr_HD$aggregate()
index_HD
fit2 <- rr_HD$learners[[1]]

rr_HD$resampling$train_set(1)
task <- as_task_surv(expr.surv, time = "ACM", event = "ACM_Censor")
task$select(rid)
task
task_train <- task$filter(rr_HD$resampling$train_set(1))
task_train
task <- as_task_surv(expr.surv, time = "ACM", event = "ACM_Censor")
task$select(rid)
task
task_test <- task$filter(rr_HD$resampling$test_set(1))
task_test
task <- as_task_surv(expr.surv, time = "ACM", event = "ACM_Censor")
task$select(rid)
task
task_meta <- task
task_meta

fit2 <- rr_HD$learners[[1]]
fit2$predict(task_test)$score(msrs(measures))
fit2$predict(task_train)$score(msrs(measures))
fit2$predict(task_meta)$score(msrs(measures))

val_dd_list2 <- list()
val_dd_list2[[1]] <- task_train$data()
val_dd_list2[[2]] <- task_test$data()
val_dd_list2[[3]] <- task_meta$data()
names(val_dd_list2) <- c("Train_1", "Test_2", "Meta_3")

rs2 <- lapply(val_dd_list2, function(x) {
  dat.mat <- x %>% as.matrix()
  dtrain <- list(
    data = dat.mat[, 3:ncol(dat.mat), drop = F],
    label = dat.mat[, "ACM"] * (-(-1)^(as.numeric(dat.mat[, "ACM_Censor"])))
  )
  Dtrain <- xgb.DMatrix(dtrain$data, label = dtrain$label)
  RS <- predict(fit2$model, newdata = Dtrain, type = "risk")
  cbind(x[, 1:2], RS = RS)
})
C_index <- sapply(rs2, function(x) {
  concordance.index(scale(x$RS),
    surv.time = x$ACM,
    surv.event = x$ACM_Censor,
    method = "noether"
  )$c.index
})
C_index


load( 'val_dd_list.rda')
rs <- lapply(val_dd_list,function(x){
  task=as_task_surv(x,time="ACM",event="ACM_Censor")
  RS = fit$predict(task)$crank
  cbind(x[,1:2],RS=RS)
})
C_index <- sapply(rs,function(x){
  concordance.index(scale(x$RS),
                    surv.time = x$ACM,
                    surv.event = x$ACM_Censor,
                    method = "noether")$c.index
});C_index

library(xgboost)
library(scales)

std1 <- function(x){
  return ((x - min(x, na.rm = T))/(max(x, na.rm = T) - min(x, na.rm = T)))
}


shap.score.rank <- function(xgb_model = xgb_mod, shap_approx = TRUE,
                            X_train = mydata$train_mm) {
  require(xgboost)
  require(data.table)
  shap_contrib <- predict(xgb_model, X_train,
    predcontrib = TRUE, approxcontrib = shap_approx
  )
  shap_contrib <- as.data.table(shap_contrib)
  shap_contrib[, BIAS := NULL]
  cat("make SHAP score by decreasing order\n\n")
  mean_shap_score <- colMeans(abs(shap_contrib))[order(colMeans(abs(shap_contrib)), decreasing = T)]
  return(list(
    shap_score = shap_contrib,
    mean_shap_score = (mean_shap_score)
  ))
}


shap.prep <- function(shap = shap_result, X_train = mydata$train_mm, top_n) {
  require(ggforce)
  std1 <- function(x) {
    return((x - min(x, na.rm = T)) / (max(x, na.rm = T) - min(x, na.rm = T)))
  }
  # descending order
  if (missing(top_n)) top_n <- dim(X_train)[2] # by default, use all features
  if (!top_n %in% c(1:dim(X_train)[2])) stop("supply correct top_n")
  require(data.table)
  shap_score_sub <- as.data.table(shap$shap_score)
  shap_score_sub <- shap_score_sub[, names(shap$mean_shap_score)[1:top_n], with = F]
  shap_score_long <- melt.data.table(shap_score_sub, measure.vars = colnames(shap_score_sub))

  # feature values: the values in the original dataset
  fv_sub <- as.data.table(X_train)[, names(shap$mean_shap_score)[1:top_n], with = F]
  # standardize feature values
  fv_sub_long <- melt.data.table(fv_sub, measure.vars = colnames(fv_sub))
  fv_sub_long[, stdfvalue := std1(value), by = "variable"]
  # SHAP value: value
  # raw feature value: rfvalue;
  # standarized: stdfvalue
  names(fv_sub_long) <- c("variable", "rfvalue", "stdfvalue")
  shap_long2 <- cbind(shap_score_long, fv_sub_long[, c("rfvalue", "stdfvalue")])
  shap_long2[, mean_value := mean(abs(value)), by = variable]
  setkey(shap_long2, variable)
  return(shap_long2)
}


plot.shap.summary <- function(data_long) {
  x_bound <- max(abs(data_long$value))
  require("ggforce") # for `geom_sina`
  plot1 <- ggplot(data = data_long) +
    coord_flip() +
    labs(
      title = "SHapley Additive exPlanations", x = "",
      y = "SHAP value (Impact on Model Output)",
      color = "Feature Value"
    ) +
    # sina plot:
    geom_sina(aes(x = variable, y = value, color = stdfvalue), size = 1.7) +
    # print the mean absolute value:
    geom_text(
      data = unique(data_long[, c("variable", "mean_value"), with = F]),
      aes(x = variable, y = -Inf, label = sprintf("%.4f", mean_value)),
      size = 3, alpha = 0.7,
      hjust = -0.2,
      fontface = "bold"
    ) + # bold
    # theme_classic(base_rect_size = 1.5) +
    theme_bw(base_rect_size = 1.65) +
    guides(fill = guide_legend(title.position = "right")) +
    # # add a "SHAP" bar notation
    # annotate("text", x = -Inf, y = -Inf, vjust = -0.2, hjust = 0, size = 3,
    #          label = expression(group("|", bar(SHAP), "|"))) +
    # scale_color_gradient(low="#FFCC33", high="#6600CC",
    #                      breaks=c(0,1), labels=c("Low","High")) +
    scale_color_gradient2(
      low = "#5AB4C2", mid = "white", high = "#E36258",
      labels = c("Low", "", "High"), breaks = c(0, 0.5, 1),
      midpoint = 0.5 # breaks=c(0,1), labels=c("Low",'0',"High")
    ) +
    theme(
      axis.title.x = element_text(size = 10, colour = "black", face = "bold", vjust = .01),
      axis.title.y = element_text(size = 12, colour = "grey15", face = "bold", vjust = 2),
      plot.title = element_text(size = 12, colour = "darkred", face = "bold", hjust = .6),
      axis.text = element_text(size = 9, face = "bold"),
      axis.ticks = element_blank(),
      axis.line.y = element_blank(),
      # axis.line.x = element_line( color = 'black',size = .8 ),

      panel.grid.major = element_line(color = "white", size = .8, linetype = "solid"),
      panel.grid.minor = element_line(color = "white", size = .5, linetype = "solid"),

      # panel.background = element_rect(fill='white'),
      panel.background = element_rect(fill = scales::alpha("#F0F8FF", .7)),
      legend.key.height = unit(27, "mm"),
      legend.key.width = unit(1.3, "mm"),
      legend.position = "right"
    ) +
    geom_hline(yintercept = 0, color = scales::alpha("grey80", 1), size = .65, linetype = "dashed") + # the vertical line
    # geom_hline(yintercept = 0,color = scales::alpha('white',1),size= 1.0,linetype = "solid") + # the vertical line

    scale_y_continuous(limits = c(-x_bound, x_bound)) +
    # reverse the order of features
    scale_x_discrete(limits = rev(levels(data_long$variable)))

  return(plot1)
}


dat.mat <- val_dd_list$Meta_3 %>% as.matrix()
dat.mat[, c(3:14)] <- scale(dat.mat[, c(3:14)])

minmax <- function(x) {
  x <- (x - min(x)) / (max(x) - min(x))
}
dat.mat[, c(3:14)] <- apply(dat.mat[, c(3:14)], 2, minmax)


dtrain <- list(
  data = dat.mat[, 3:ncol(dat.mat), drop = F],
  label = dat.mat[, "ACM"] * (-(-1)^(as.numeric(dat.mat[, "ACM_Censor"])))
)
Dtrain <- xgb.DMatrix(dtrain$data, label = dtrain$label)
shap_result <- shap.score.rank(
  xgb_model = fit$model,
  X_train = Dtrain,
  shap_approx = F
)

shap_long_hd <- shap.prep(shap = shap_result, X_train = dat.mat, top_n = 12)
shapplot <- plot.shap.summary(data_long = shap_long_hd)
shapplot
ggsave(shapplot,
  filename = c("shapplot.pdf"),
  width = 6.9,
  height = 6
)
ggsave(shapplot,
  filename = c("shapplot2.pdf"),
  width = 6.9,
  height = 5.2
)



###########' @Heatmap

clin <- lp.ctree2$Meta_3 %>%
  dplyr::select(
    group, ACM, ACM_Censor,
    Gender, Age, Alcohol, Smoking,
    CKD_stage, NYHA, HF_subtype,
    CAD, Arrhythmia, CCB, HTN
  )
str(clin)

clin$ACM_Censor <- ifelse(clin$ACM_Censor == 1, "Dead", "Alive")
clin$Gender <- ifelse(clin$Gender == 1, "Male", "Female")
clin$Age <- ifelse(clin$Age >= 65, ">65", "≤65")
clin$Alcohol <- ifelse(clin$Alcohol == 1, "Yes", "No")
clin$Smoking <- ifelse(clin$Smoking == 1, "Yes", "No")
clin <- clin %>% mutate(
  CKD_stage = case_when(
    CKD_stage %in% 1 ~ "I",
    CKD_stage %in% 2 ~ "II",
    CKD_stage %in% 3 ~ "III",
    CKD_stage %in% 4 ~ "IV",
    CKD_stage %in% 5 ~ "V"
  )
)
clin <- clin %>% mutate(
  NYHA = case_when(
    NYHA %in% 1 ~ "I",
    NYHA %in% 2 ~ "II",
    NYHA %in% 3 ~ "III",
    NYHA %in% 4 ~ "IV"
  )
)
clin <- clin %>% mutate(
  HF_subtype = case_when(
    HF_subtype %in% 1 ~ "HFpEF",
    HF_subtype %in% 2 ~ "HFmrEF",
    HF_subtype %in% 3 ~ "HFrEF"
  )
)
clin <- clin %>% mutate(
  HTN = case_when(
    HTN %in% 0 ~ "No",
    HTN %in% 1 ~ "I",
    HTN %in% 2 ~ "II",
    HTN %in% 3 ~ "III"
  )
)
clin$CAD <- ifelse(clin$CAD == 1, "Concomitant", "No")
clin$Arrhythmia <- ifelse(clin$Arrhythmia == 1, "Concomitant", "No")
clin$CCB <- ifelse(clin$CCB == 1, "Concomitant", "No")


A1 <- "#1e8b9b"
A2 <- "#ff8c3e"
Age <- c(alpha(A1, 0.6), alpha(A2, 0.6))
rm(A1, A2)
names(Age) <- c("≤65", ">65")


gender1 <- "#3C5E95"
gender2 <- "#C2BFD3"
Gender <- c(alpha(gender1, 0.6), alpha(gender2, 0.6))
names(Gender) <- c("Male", "Female")
rm(gender1, gender2)

A1 <- "#B0997F"
A2 <- "#93a8ac"
Alcohol <- c(alpha(A1, 0.6), alpha(A2, 0.6))
rm(A1, A2)
names(Alcohol) <- c("Yes", "No")

A1 <- "#FF6666"
A2 <- "#119da4"
Smoking <- c(alpha(A1, 0.6), alpha(A2, 0.6))
rm(A1, A2)
names(Smoking) <- c("Yes", "No")

G1 <- "#00F5FF"
G2 <- "#40E0D0"
G3 <- "#00C5CD"
G4 <- "#0086BB"
G5 <- "#007FFF"
CKD_stage <- c(alpha(G1, 0.45), alpha(G2, 0.45), alpha(G3, 0.45), alpha(G4, 0.45), alpha(G5, 0.45))
rm(G1, G2, G3, G4, G5)
names(CKD_stage) <- c("I", "II", "III", "IV", "V")

S1 <- "#F0FFFF"
S2 <- "#E0EEEE"
S3 <- "#C1CDCD"
S4 <- "#838B8B"
NYHA <- c(alpha(S1, 0.6), alpha(S2, 0.6), alpha(S3, 0.6), alpha(S4, 0.6))
rm(S1, S2, S3, S4)
names(NYHA) <- c("I", "II", "III", "IV")

S1 <- "#76BDCF"
S2 <- "#CE75AD"
S3 <- "#94376C"
HF_subtype <- c(alpha(S1, 0.6), alpha(S2, 0.6), alpha(S3, 0.4))
rm(S1, S2, S3)
names(HF_subtype) <- c("HFpEF", "HFmrEF", "HFrEF")

A1 <- "#8AB6C9"
A2 <- "#FBC2A6"
A3 <- "#FBC2A6"
A4 <- "grey"
HTN <- c(alpha(A1, 0.6), alpha(A2, 0.6), alpha(A3, 0.6), alpha(A4, 0.6))
rm(A1, A2, A3, A4)
names(HTN) <- c("No", "I", "II", "III")

N1 <- "#AA8780"
N2 <- "#F6B4A6"
CAD <- c(alpha(N1, 0.6), alpha(N2, 0.6))
rm(N1, N2)
names(CAD) <- c("Concomitant", "No")

M1 <- "#53868B"
M2 <- "#98F5FF"
Arrhythmia <- c(alpha(M1, 0.6), alpha(M2, 0.6))
rm(M1, M2)
names(Arrhythmia) <- c("Concomitant", "No")

CP1 <- "#395228"
CP2 <- "#25361E"
CCB <- c(alpha(CP1, 0.6), alpha(CP2, 0.6))
rm(CP1, CP2)
names(CCB) <- c("Concomitant", "No")

str(clin)
clin <- clin %>% arrange(group)


green <- "#FF9E4A"
cyan <- "#3CB7CC"
blue <- "#9C9290"
group <- c(alpha(green, 0.6), alpha(cyan, 0.6), alpha(blue, 0.6))
rm(green, cyan, blue)
names(group) <- c("Low risk", "Intermediate risk", "High risk")

green <- "#7CC7CA"
cyan <- "#4BA8D5"
blue <- "#1A84C1"
group <- c(scales::alpha(green, 0.6), scales::alpha(cyan, 0.6), scales::alpha(blue, 0.6))
rm(green, cyan, blue)
names(group) <- c("Low risk", "Intermediate risk", "High risk")


C1 <- "#FF6666"
C2 <- "#93a8ac"
ACM_Censor <- c(scales::alpha(C1, 0.6), scales::alpha(C2, 0.6))
rm(C1, C2)
names(ACM_Censor) <- c("Dead", "Alive")

if (T) {
  ha <- HeatmapAnnotation(
    group = clin$group,
    show_legend = T,
    ACM_Censor = clin$ACM_Censor,
    Gender = clin$Gender, Age = clin$Age, Smoking = clin$Smoking,
    CKD_stage = clin$CKD_stage, NYHA = clin$NYHA, HF_subtype = clin$HF_subtype,
    CAD = clin$CAD, Alcohol = clin$Alcohol, Arrhythmia = clin$Arrhythmia,
    HTN = clin$HTN, CCB = clin$CCB, na_col = "white",
    annotation_legend_param = list(
      group = list(title = "group"),
      ACM_Censor = list(title = "Alive"),
      Gender = list(title = "Gender"),
      Age = list(title = "Age"),
      Smoking = list(title = "Smoking"),
      CKD_stage = list(title = "CKD_stage"),
      NYHA = list(title = "NYHA"),
      HF_subtype = list(title = "HF_subtype"),
      CAD = list(title = "CAD"),
      Alcohol = list(title = "Alcohol"),
      Arrhythmia = list(title = "Arrhythmia"),
      CCB = list(title = "CCB"),
      HTN = list(title = "HTN"),
      labels_gp = gpar(fontsize = 8),
      title_gp = gpar(fontsize = 10),
      ncol = 1
    ),
    gap = unit(c(1, rep(1, 10), 0), "mm"),
    col = list(
      group = group,
      ACM_Censor = ACM_Censor,
      Gender = Gender,
      Age = Age,
      Smoking = Smoking,
      CKD_stage = CKD_stage,
      NYHA = NYHA,
      HF_subtype = HF_subtype,
      CAD = CAD,
      Alcohol = Alcohol,
      Arrhythmia = Arrhythmia,
      CCB = CCB,
      HTN = HTN
    ),
    show_annotation_name = TRUE,
    annotation_name_gp = gpar(fontsize = 10),
    annotation_name_side = "left",
    annotation_height = unit(rep(5, 10), "mm"), border = T
  )


  col_fun <- colorRamp2(c(-2, 0, 2), c(pal_npg("nrc", alpha = 0.6)(9)[2], "white", pal_npg("nrc", alpha = 0.9)(9)[1]))

  hm <- t(data.frame(row.names = rownames(clin), d_e_l_e_t = rep(0, nrow(clin))))

  ht <- Heatmap(hm,
    name = "Z-score", # col = col_fun,
    height = 0,
    cluster_rows = TRUE,
    cluster_columns = FALSE,
    show_row_names = F,
    show_column_names = FALSE,
    top_annotation = ha,
    column_title = " ",
    border_gp = gpar(col = "black", lty = 2, lwd = 8, linejoin = "round"),
    border = F,
    row_names_side = "right",
    column_gap = unit(c(0.3), "cm"),
    row_gap = unit(c(0.3), "cm"),
    column_split = clin$group,
    show_heatmap_legend = F
  )
  ht
}


pdf("heatmap__ctree.pdf",
  width = 13, height = 6
)
ht
dev.off()






